const tintColor = '#007AFF';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  iOSBlue: tintColor,
  iOSGreen: '#49d662',
  iOSRed: '#ff453a',
  iOSBorder: '#DBDBDB',
  themeBackground: '#fafafa',
  screenHeaderBackground: '#fff',
  modalHeaderBackground: '#fff',
  textPrimary: '#000',
  iOSLightBackground: '#F7F7F7',
  iconLight: 'rgba(0,0,0,0.35)',
  reminderCardBorder: '#DBDBDB',
  reminderCardBackground: '#fff',
};
